### ISSUE TITLE
Single Precision Post Processing Does not Work

### ISSUE THREAD

**Issue by wilfonba** [MFlowCode/MFC#102]
Post process calls MPI_ABORT with no error messages when single precision is specified.

**Comment by sbryngelson** [comment]
single precision specified how? this is too vague.

**Comment by sbryngelson** [comment]
I meant what options are you using for `parallel_IO` and `format` and so on...

**Comment by wilfonba** [comment]
'format'               : 1,
'precision'.          : 1,
'prim_vars_wrt'  : 'T'
'parallel_io'         : 'T'

**Comment by wilfonba** [comment]
Compiling with GNU shows the real problem:

"Unsupported combination of precision and parallel IO. Please use precision == 2 when enabling parallel_io.  Exiting ..."

It appears it's simply not been implemented yet. NVHPC doesn't show these error messages for checking the input files.

**Comment by sbryngelson** [comment]
This seems to signal a more significant problem. The GNU compilers are respecting our `m_start_up.f90` checks (where this error comes from), but NVHPC compilers are not.

**Comment by wilfonba** [comment]
On a similar note, there appears to be an undocumented input option "coarsen_silo" that shows up in the post-processing code and appears to write silo_files using the precision variable.

https://github.com/MFlowCode/MFC/blob/b5fd492a00bdd701af96ae2b6e4f989b52d3baac/src/post_process/m_data_output.f90#L689-L702

**Comment by sbryngelson** [comment]
yes this should be re-tested then documented.
