### ISSUE TITLE
NVHPC not respecting startup checks

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC#115]
From #102 

---
@wilfonba 

Compiling with GNU shows the real problem:

"Unsupported combination of precision and parallel IO. Please use precision == 2 when enabling parallel_io. Exiting ..."

It appears it's simply not been implemented yet. NVHPC doesn't show these error messages for checking the input files.

---
@sbryngelson

This signals a more significant problem. The GNU compilers are respecting our m_start_up.f90 checks (where this error comes from), but NVHPC compilers are not.

**Comment by anshgupta1234** [comment]
Interesting, I just tested this on Phoenix with NVHPC and it did catch the error:

<img width="1645" alt="image" src="https://user-images.githubusercontent.com/38015438/223568493-06920641-6506-4f1c-b6e1-702977814d8a.png">

Looking at the code, there aren't really any pre-processor directives associated with GNU/NVHPC compilers when calling `m_start_up`. The only conditional I see is checking if proc_rank == 0 before calling `s_check_input_file()`.

@wilfonba I did notice that the error message is sandwiched in between MPI error messages. Perhaps it did print but went unnoticed?

**Comment by wilfonba** [comment]
I think what's actually happening on Summit is that MPI_abort() is called before the print statement is flushed to stdout. I know in C/C++ a simple fix for this would be to call "fflush(stdout)" after every print statement in the input checking code, and an equivalent solution would be very easy to add to MFC if it exists. I think "call flush()" before every "call MPI_Abort()" in these input-checking files may be enough to fix this issue. Summit seems to buffer output in different ways than other computers, ie. output is displayed in the terminal every few hundred-time steps in some cases. I'll take a look at "call flush()" and its effect this evening. @anshgupta1234 @sbryngelson

**Comment by sbryngelson** [comment]
Interesting -- I did not know about this. Would an `mpi_barrier()` of some kind fix it? Meaning that _one_ of the MPI ranks is getting to `mpi_abort()` before the print statement, so nothing is printing. If you put a barrier before the print statement, it would have to wait, then print, then abort. I assume this is somewhere in the actual `s_mpi_abort()` subroutine in `m_mpi_common`.

**Comment by sbryngelson** [comment]
Ok so what if changed this routine:
https://github.com/MFlowCode/MFC/blob/d929c4b1f40633330314bc87ee22495144acfe3f/src/common/m_mpi_common.fpp#L313-L326

to instead have an optional character argument that prints before aborting? 
something like 
```
subroutine s_mpi_abort(prnt)
	character(len=*), intent(in), optional :: prnt
     
    if (present(prnt)) then
        print*, print
    end if

#ifndef MFC_MPI
        stop 1
#else
		! wait for MPI ranks!!
		call MPI_Barrier(MPI_COMM_WORLD, ierr)
        ! Terminating the MPI environment
        call MPI_ABORT(MPI_COMM_WORLD, 1, ierr)
#endif
    end subroutine s_mpi_abort
```


However, thinking more about this, I don't know why the `PRINT` statement already in MFC pre/post process before `s_mpi_abort()` doesn't print for _every_ MPI rank already (meaning my hypothesis could be wrong). 
https://github.com/MFlowCode/MFC/blob/d929c4b1f40633330314bc87ee22495144acfe3f/src/pre_process/m_start_up.fpp#L217-L221C13
For example, for a 128 core job it seems like it should print that statement 128 times as present, and I'm not sure why it doesn't. Regardless,

**Comment by sbryngelson** [comment]
If there's one thing I know for sure, it's the above change would shorten the code length!

**Comment by henryleberre** [comment]
@sbryngelson I don't think you need to wait for all MPI ranks but it might be useful if MFC does some clean up operations beforehand and you want to make sure that they complete. In that case, I would add `if (proc_rank .eq. 0)` before printing. As an extra caution, I would still add an `fflush` just to make sure.

**Comment by sbryngelson** [comment]
@henryleberre agreed.

**Comment by wilfonba** [comment]
@henryleberre Wouldn't adding if (proc_rank == 0) cause problems if this function is called from a different rank?

**Comment by henryleberre** [comment]
@wilfonba Indeed, just like the `MPI_Barrier` it would cause problems if this wasn't called on all ranks.. One solution is to have a timeout. It depends how we want to use `s_mpi_abort`.

**Comment by wilfonba** [comment]
@sbryngelson the pull request I made currently works, as far as I can tell. Most of the calls to s_mpi_abort are in m_start_up files which are only ran on one processor, so dealing with MPI_ranks isn't necessary.
