### ISSUE TITLE
Files in docs don't exist

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC#121]
https://mflowcode.github.io/documentation/templates/

linked from

https://mflowcode.github.io/documentation/md_running.html

doesn't exist. we should have a check to make sure all links exist before pushing...

**Comment by sbryngelson** [comment]
this one doesn't either

https://mflowcode.github.io/documentation/examples/2D_shockbubble/

linked from the same url

**Comment by sbryngelson** [comment]
this doesn't exist either

https://mflowcode.github.io/documentation/src/simulation/

**Comment by sbryngelson** [comment]
this doesn't exist: https://mflowcode.github.io/documentation/toolchain/mfc/tests/cases.py

linked from

https://mflowcode.github.io/documentation/md_testing.html

**Comment by sbryngelson** [comment]
```Then, it uses the [h5py](https://www.h5py.org/) library to ensure that there are no NaNs or Infinity's written to the silo files. Although adding this option does not guarantee that accurate silo files are generated, it does ensure that post process does not fail or produce malformed data.```

out of date

**Comment by anshgupta1234** [comment]
I believe #122 closed this.
