### ISSUE TITLE
Equation of state is not DRY

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC#13]
The equation of state is used to compute the pressure from the variables. This EOS changes slightly for different models. The EOS implementation is repeated several places in the code, including in `m_variables_converison`, `m_data_output` (including serial data output and probe outputs), and likely more. Following the [DRY principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) (don't repeat yourself), we should fix this. It has also caused multiple false bugs in the past.

**Comment by anshgupta1234** [comment]
I have gone ahead and implemented the `s_compute_pressure` subroutines and pointers, located in `m_initial_condition.fpp`. However, because `m_initial_condition.fpp` uses `m_variables_conversion.fpp` and `m_variables_conversion.fpp` uses `m_initial_condition.fpp`, there is an error being thrown:

```
~/src/pre_process/m_variables_conversion.f90:19:9:

   19 |     use m_initial_condition
      |         1
Error: 'm_variables_conversion' of module 'm_initial_condition', imported at (1), is also the name of the current program unit
```

Therefore I am unsure if there's any way I can really implement `s_compute_pressure` in `m_initial_condition`. Is there any other module that I can try and implement it in?

**Comment by sbryngelson** [comment]
I think `m_variable_conversion` is a more natural home for this kind of thing.

**Comment by sbryngelson** [comment]
@anshgupta1234 Check out these lines in `m_cbc`:

https://github.com/MFlowCode/MFC/blob/d80602abfc6c1528708963032ef8cd44b3f26622/src/simulation/m_cbc.fpp#L786-L853

I think these can probably be factored out completely. One thing we didn't initially notice is how pervasive the computation of `c`, the speed of sound is. 
This is above, but also throughout the codebase. 
We should create a helper function that goes in `common/m_var_conversion` that computes the speed of sound.

We see something similar in `m_riemann_solvers`, for example:
https://github.com/MFlowCode/MFC/blob/d80602abfc6c1528708963032ef8cd44b3f26622/src/simulation/m_riemann_solvers.fpp#L464-L572

We also see the computation of `c` coming up again. Each time it takes something like 70 lines:

https://github.com/MFlowCode/MFC/blob/d80602abfc6c1528708963032ef8cd44b3f26622/src/simulation/m_riemann_solvers.fpp#L639-L714

**Comment by sbryngelson** [comment]
I realize this is becoming an omnibus "issue". Let's merge your pull request when you have all of the main variables conversion stuff done, then do speed of sound `c` after.
