### ISSUE TITLE
Clean up isentropic vortex, turn into `example/`

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC#177]
A super easy issue: Create a big red diff by leveraging the merged PR #176 to get rid of the hard-coded isentropic vortex case of [this paper](https://authors.library.caltech.edu/49575/7/nihms606496.pdf) (fig 4 sec 4.4) that lives in at least three different places as `patch_icpp(patch_id)%geometry == 6`. In the process can also kill the documentation we have on this patch type (if it exists). Here are some code snippets:

https://github.com/MFlowCode/MFC/blob/aad787bf90a371e87aa441d6e8ac3ff019cf2625/src/pre_process/m_assign_variables.f90#L156-L205

https://github.com/MFlowCode/MFC/blob/aad787bf90a371e87aa441d6e8ac3ff019cf2625/src/pre_process/m_assign_variables.f90#L570-L609

https://github.com/MFlowCode/MFC/blob/aad787bf90a371e87aa441d6e8ac3ff019cf2625/src/pre_process/m_assign_variables.f90#L773-L812

**Comment by RasmitDevkota** [comment]
Once the isentropic vortex code becomes an example case, would it make sense to get rid of vortex geometry 6 in its entirety as it isn't necessary for simulating such scenarios?

**Comment by sbryngelson** [comment]
Yes, that's the goal.

**Comment by sbryngelson** [comment]
Closed by #205
