### ISSUE TITLE
Adding boundary conditions that already exist in forks

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC#185]
Several boundary conditions have been added to MFC in various forks. 
I would like to merge these via isolated PRs as soon as possible. 

For example:
- [x] @wilfonba non-characteristic no-slip wall
- [x] @wilfonba non-characteristic slip wall (also please fix documentation on current slip wall)
- [x] characteristic slip wall
- [ ] @haochey characteristic no-slip wall
- [x] @anshgupta1234 inlet boundary condition (or was this @haochey)

Be careful that if you give your BC a number that is `<= -5` then the code will interpret it as a CBC, which you might not want:
https://github.com/MFlowCode/MFC/blob/1aefc097fea9acff82819634a161114b9411d5fe/src/simulation/m_rhs.fpp#L877-L885

We have to re-organize the boundary conditions so that this logic is not a problem or is otherwise resolved somehow.

Related to issue #187 and #186

**Comment by sbryngelson** [comment]
Also relevant! 
https://github.com/anandrdbz/MFC/blob/9140e50e9a99bba74d68956fe18799b9c3fdce4d/src/simulation/m_start_up.fpp#L561-L579

**Comment by wilfonba** [comment]
Non-characteristic no-slip and slip walls have been added and merged to the master branch.

**Comment by sbryngelson** [comment]
@haochey can you post the status of characteristic no-slip walls? Or did they have that specific corner problem making them challenging to use?

**Comment by sbryngelson** [comment]
@wilfonba do we have a characteristic slip wall, or no?

**Comment by wilfonba** [comment]
Yes, characteristics slip walls have been in the code for a while now.

**Comment by haochey** [comment]
> @haochey can you post the status of characteristic no-slip walls? Or did they have that specific corner problem making them challenging to use?

Characteristic no-slip wall works in 2D by treating the corners as slip wall nevertheless it's not perfect because the velocity is not perfectly zero in the wall. It's shown in the animation below. This method does not resolve the corner/edge issue in 3D (i.e. cases still crashing in 3D). 

https://github.com/MFlowCode/MFC/assets/98496194/89c58ad7-0a67-4d95-bf72-94d37107ce54

**Comment by sbryngelson** [comment]
Thanks @haochey I am closing this issue.
