### ISSUE TITLE
Lax shock tube problem examples isn't generating visualizations on website

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC#191]
The PR for the Lax shock tube didn’t create the appropriate visualizations for the example case. For example: https://mflowcode.github.io/documentation/md_examples.html

The relevant PR is here: https://github.com/MFlowCode/MFC/pull/190

Which might be compared against the PR that introduced those first test cases here: https://github.com/MFlowCode/MFC/pull/176

(This issue is for @RasmitDevkota)

**Comment by henryleberre** [comment]
Assuming @RasmitDevkota will be working on this: [this file](https://github.com/MFlowCode/MFC/blob/master/docs/examples.sh) and some CMake configuration takes care of updating the website/docs with the correct markdown and embedding the images. Following the same directory/markdown format as [examples/1D_shuosher](https://github.com/MFlowCode/MFC/tree/master/examples/1D_shuosher) should suffice. I had made my own script to generate these visualizations: [misc/viz.py](https://github.com/MFlowCode/MFC/blob/master/misc/viz.py). It works using files generated when running `pre_process`/`simulation` with `parallel_io=F`. (It also works if using multiple ranks)
