### ISSUE TITLE
Progress bar!

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC#199]
Would be curious to see an implementation of this in MFC for the time stepping (especially since each time step takes about the same amount of time): https://github.com/zoziha/progress-bar/ 

We cannot use the `fpm` version and it would have to be added as a module in `common/` or something. 

Easy first issue to try out.

**Comment by wilfonba** [comment]
Relevant Github repo: https://github.com/macie/fortran-libs/tree/master

**Comment by MagBad** [comment]
Another implementation, for a progress bar/meter, can be found here: https://github.com/szaghi/forbear

And another question (as I might want to start contributing to MFC) how should the progress bar handle the MPI specifics? My assumption would be that the meter is only relevant for the 'master' rank.

**Comment by sbryngelson** [comment]
Thanks, @MagBad! Could you be a bit more specific? Maybe copy a few lines of code that are relevant to your concern? The code is full of MPI calls. But if I guess at what you're getting at - you are correct, the progress bar need only concern itself with the master rank (e.g., check out these lines: https://github.com/MFlowCode/MFC/blob/0495ba8e8aca5dd1f53c1edf73ee51b02bbeae5c/src/simulation/m_start_up.fpp#L860-L894)

**Comment by henryleberre** [comment]
@sbryngelson I am not sure if you are aware but when generating STL patches we show the percentage completion on a single line, it updates itself as needed. It is not a progress bar but moreso a progress indicator. The main issue with progress bars & indicators is that they only really work interactively. We would probably want to keep the current system as a fallback for batch jobs.

**Comment by henryleberre** [comment]
Also, I will add that it shouldn't be too complicated to import these modules.

**Comment by sbryngelson** [comment]
You're correct. I'm not sure how to best dispatch this feature in a batch setting without adding additional frivolous logic to the code.

**Comment by MagBad** [comment]
Yes @sbryngelson that's the part I've been concerned with. I'm still digging through the code. Thanks for providing the code line.
I'm not 100% sure how the _usual_ environment, in which MFC runs at, is configured. If it runs on a HPC cluster 'somewhere' else, the progress bar shouldn't really matter. As @henryleberre highlighted as well.
On the other hand, if it runs locally i.e. on one's computer, it might make sense to have it.

So maybe it would be an idea to make it a runtime option in the `case.py` files IIRC?

The forbear library could provide a wide variety of indicators: percentage, time estimations, ... see its [main features in the README.md](https://github.com/szaghi/forbear/blob/master/README.md#main-features).

Since most progress bars work with a carriage return character, it would spam log files. Does MFC use any of those? Otherwise, the used unit should be different. But that might not be a problem for this issue at the current time. 

IMHO having a progress bar (on the master rank) that can be activated at runtime should suffice.

**Comment by sbryngelson** [comment]
@MagBad one cannot put the progress indicator in `case.py` because those files indicate the physics/numerical method, not the manner in which the case is run. For example, a batch job via SLURM on a cluster vs. interactively on your command line with you watching. So, differentiating between interactive and batch jobs would have to be done at the `toolchain/` level, making that code more complicated and eventually invoking some option dynamically at runtime in the Fortran source. I think this is likely a bad idea: little reward for the added complexity.

If there's an appropriate status bar that can be used in both batch and interactive sessions, then that would be great. Right now, MFC prints a new line every time a new time step is reached (or every `t_step_save` steps). I'm not sure how to rectify this so that the output files from a batch run _and_ an interactive session would both look reasonable. One way to find out is to just integrate the status bar and run a batch job and find out.

**Comment by henryleberre** [comment]
I wouldn't be surprised if these libraries supported this use case as it's effectively the same as redirecting stdout/stderr to a file.

**Comment by MagBad** [comment]
@sbryngelson Okay maybe I've understood something wrong. Maybe a short explanation of my train of thought explains it better.
From the [https://github.com/MFlowCode/MFC/blob/master/examples/1D_bubblescreen/case.py#L76](1D_bubblescreen/case.py#) you simply add

```
 # Logistics ================================================
    'run_time_info'                : 'T',
    'progress_meter'               : 'T',
```

Which would enable it. From the structure of the case files, I thought that this would be possible. I'll dig through the code and double check that assumption.



> I wouldn't be surprised if these libraries supported this use case as it's effectively the same as redirecting stdout/stderr to a file.
I'd assume that as well. I'm going to check this as well as @henryleberre mentioned: it's best to run it.

**Comment by sbryngelson** [comment]
> I wouldn't be surprised if these libraries supported this use case as it's effectively the same as redirecting stdout/stderr to a file.

Might be right - I'm glad to find out.

**Comment by sbryngelson** [comment]
> @sbryngelson Okay maybe I've understood something wrong. Maybe a short explanation of my train of thought explains it better. From the [https://github.com/MFlowCode/MFC/blob/master/examples/1D_bubblescreen/case.py#L76](1D_bubblescreen/case.py#) you simply add
> 
> ```
>  # Logistics ================================================
>     'run_time_info'                : 'T',
>     'progress_meter'               : 'T',
> ```
> 
> Which would enable it. From the structure of the case files, I thought that this would be possible. I'll dig through the code and double check that assumption.
> 
> > I wouldn't be surprised if these libraries supported this use case as it's effectively the same as redirecting stdout/stderr to a file.
> > I'd assume that as well. I'm going to check this as well as @henryleberre mentioned: it's best to run it.

@MagBad The reason this new option in `case.py` might not work as well as it might appear is that, if there truly is a problem with the batch vs. interactive output with a progress indicator, then that would have to be controlled at the level of `./mfc.sh` (and into the toolchain). This isb because the toolchain and the `mfc.sh` script file are the files that "know" what "mode" MFC is running in (batch or interactive). 

Of course, if there is no problem dumping the progress bar output into stdout or stderr or whatever then this option you introduce above is unnecessary entirely.

**Comment by sbryngelson** [comment]
Not planning on working on this, so closing.
