### ISSUE TITLE
Test suite does not touch any `--case-optimization` cases

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC#225]
The current test suite does not do any case optimization cases. Is it possible to compile a single test case that uses all the case optimization parameters (bubbles, 3D, etc.) and add it as a one-off test? would this double the run-time of our test suite?

**Comment by henryleberre** [comment]
This should be rather straightforward to add. It would currently require two partial rebuilds of `simulation` (once for a `--case-optimization` case and once for all others) as well as the serialization of the `--case-optimization` test case(s) - you would run into issues with running multiple of these cases concurrently. The cost is probably negligeable, however. There are was we could get around this but it would most likely be over-engineering.

**Comment by sbryngelson** [comment]
`--case-optimization` could be added to the test suite matrix for one select case that has "all the case optimization features" and for a couple select runners (at least one CPU and one GPU). This seems like the most straightforward solution.

**Comment by sbryngelson** [comment]
This can be closed because benchmarking runs case optimization cases, so we will know if it breaks (at least for the most part).
