### ISSUE TITLE
Master branch generating batch scripts with incorrect order of binaries

### ISSUE THREAD

**Issue by wilfonba** [MFlowCode/MFC#253]
Running ./mfc.sh run case.py -e batch -a <account> -w <time> -# <name> on summit generates an LSF batch file that runs syscheck -> post_process -> pre_process -> simulation. The resulting batch file is attached. 
[batch.txt](https://github.com/MFlowCode/MFC/files/13643083/batch.txt)

I've noticed this problem on my personal fork when running in batch and interactively on other machines as well.

**Comment by henryleberre** [comment]
Fixed in #248.. This is because we were using `set()`s to store the default MFC targets. We now order them by their logical "run" order when setting the default `targets` parameter.
