### ISSUE TITLE
Python min version still a problem

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC#269]
`./mfc.sh` tests the command `python3` for the Python version. This checks the "usual" Python version, such as whatever `which python3` or `type python3` shows (e.g., if one has used an alias or export to change their user space via, say, `alias python3='/usr/bin/python3.11'`, it will show that). However, the shebangs in the toolchain invoke `/usr/bin/env python3`, which ignores the userspace declarations and will give you the PATH default `python3`. A workaround for this is to create symlinks and change your path, but this is cumbersome. 

So, this issue notes two things:
* If one has python < 3.9 in their `/usr/bin/env python3`, `./mfc.sh` will not catch this and thus
* Even if one uses exports/aliases to change the user space, MFC will still fail at `./mfc.sh test`

We need a slick way to detect this. It would also be handy if MFC ran with Python aliases.

**Comment by henryleberre** [comment]
@sbryngelson does this effect users? To my knowledge, we never call the toolchain in a way that would invoke these shebangs.

**Comment by sbryngelson** [comment]
It affected me (try getting on Rogues Gallery then `ssh violet1`). The default python3 binary is python3.6 but python3.11 is in /usr/bin. No amount of exporting/aliasing seemed to get it to actually use python3.11.

**Comment by henryleberre** [comment]
@sbryngelson I think I understand the issue you were having. `mfc.sh` uses, the first time it is invoked, the standard `python3` command, to create its virtual environment using `python3 -m venv "$(pwd)/build/venv"`. It then enables it using `. build/venv/bin/activate` every time you call `mfc.sh`. The Python version it uses is therefore that which you used the first time.

To get around this, you can:
- `rm -r build/venv`
- Alias `python3` to point wherever you like!
- Call `mfc.sh` once to regenerate the virtual environment.

**Comment by sbryngelson** [comment]
> @sbryngelson I think I understand the issue you were having. `mfc.sh` uses, the first time it is invoked, the standard `python3` command, to create its virtual environment using `python3 -m venv "$(pwd)/build/venv"`. It then enables it using `. build/venv/bin/activate` every time you call `mfc.sh`. The Python version it uses is therefore that which you used the first time.
> 
> To get around this, you can:
> 
> * `rm -r build/venv`
> * Alias `python3` to point wherever you like!
> * Call `mfc.sh` once to regenerate the virtual environment.
> 
> The only file in the `toolchain` with a shebang is `mfc.py` since it's executable. It's never used though. It can help some IDEs and tools locate the entry point.

That's what I thought as well, but this does not work.
