### ISSUE TITLE
CI doesn't ensure tests/ is committed

### ISSUE THREAD

**Issue by henryleberre** [MFlowCode/MFC#292]
If your run `./mfc.sh test` on `master`, you will observe a `git diff` in case files for some tests. Per @sbryngelson's request for having test case files kept in source control, we should ensure through CI that these files are committed.

The diff currently includes some Phase Change tests (@JRChreim). A few other cases also have diffs but they still describe the same cases - physically.

**Comment by henryleberre** [comment]
Closed by #293.

**Comment by henryleberre** [comment]
Closed by #293.

**Comment by sbryngelson** [comment]
@henryleberre after rethinking this, I've come around to your point of view that keeping `case.py` test files in VC is unnecessary. It also adds to the unfortunate requirement of VC on those files (which you addressed via pr #293). 

I think a reasonable substitute is a readme file in VC in tests/ that has the stdout of the tests (can this be auto-generated?) so everyone knows what we do and don't test, e.g.:
```console
     C5B79059      1.44    1D -> bc=-9
     5EC236F2      1.50    1D -> bc=-6
     AED93D34      1.50    1D -> bc=-8
     48CCE072      1.51    1D -> bc=-7
     D79C3E6F      1.51    1D -> bc=-1
     8A59E8E6      1.51    1D -> bc=-2
     70DAE9E8      1.51    1D -> bc=-4
     3AE495F4      1.51    1D -> bc=-5
     727F72ED      0.71    1D -> bc=-10
     A60691E7      0.72    1D -> bc=-11
     3FC6FC4A      0.73    1D -> bc=-12
     2AB32975      0.73    1D -> bc=-3
     2FD933A2      0.74    1D -> bc=-15
     ED728400      0.75    1D -> bc=-16
     B3C85904      0.73    1D -> weno_order=3 -> mapped_weno=F -> mp_weno=F
     7077C99F      0.73    1D -> weno_order=3 -> mapped_weno=T -> mp_weno=F
     84017671      0.78    1D -> weno_order=5 -> mapped_weno=F -> mp_weno=F
     34580912      0.84    1D -> weno_order=5 -> mapped_weno=F -> mp_weno=T
     5527832F      0.79    1D -> 1 Fluid(s) -> riemann_solver=1 -> mixture_err
     F5890628      0.90    1D -> weno_order=5 -> mapped_weno=T -> mp_weno=F
     4AEF478A      0.86    1D -> 1 Fluid(s) -> riemann_solver=1 -> avg_state=1
     32D0F235      0.80    1D -> 1 Fluid(s) -> riemann_solver=1 -> wave_speeds=2
     F97573DB      0.81    1D -> 1 Fluid(s) -> riemann_solver=2 -> avg_state=1
     18BDCBC8      0.86    1D -> 1 Fluid(s) -> riemann_solver=2 -> mixture_err
     F4F6AC27      0.72    1D -> 1 Fluid(s) -> riemann_solver=2 -> wave_speeds=2
     2F35A1FE      0.73    1D -> 1 Fluid(s) -> riemann_solver=2 -> model_eqns=3
     8EAC3DA7      0.72    1D -> 1 Fluid(s) -> Viscous
     8E3D99E6      0.77    1D -> 1 Fluid(s) -> Viscous -> weno_Re_flux
     02748F0F      0.75    1D -> 1 Fluid(s) -> Viscous -> weno_Re_flux -> weno_avg
     1E738705      0.77    1D -> 2 Fluid(s) -> riemann_solver=1 -> mixture_err
     0879E062      0.75    1D -> 2 Fluid(s) -> riemann_solver=1 -> avg_state=1
     83EFC30C      0.78    1D -> 2 Fluid(s) -> riemann_solver=1 -> wave_speeds=2
     1CCA82F5      0.74    1D -> 2 Fluid(s) -> riemann_solver=1 -> mpp_lim
     3A8359F6      0.73    1D -> 2 Fluid(s) -> riemann_solver=2 -> mixture_err
     6D24B115      0.76    1D -> 2 Fluid(s) -> riemann_solver=2 -> avg_state=1
``` 
but without the timing data.

**Comment by henryleberre** [comment]
I understand and agree with that view. We already offer `./mfc.sh test --list`. Putting this list in source control would present a similar issue to keeping `case.py` files - but to a lesser extent.

With the benefit of hindsight, I would:
- Store the golden/pack files in a binary format.
- Store the golden files as `tests/<hash>` instead of `tests/<hash>/golden.txt`.
- Remove `tests/<hash>/case.py` & `tests/<hash>/README.md` since we have `./mfc.sh test --list -o <hash>`.

I am not sure how I feel about tracking in source control the output of `./mfc.sh test --list`. We could add this to the documentation, however, as part of its build process. Maybe in: https://mflowcode.github.io/documentation/md_testing.html.

As you said, documentation should help with this. Any thoughts?

**Comment by sbryngelson** [comment]
I wasn't aware `./mfc.sh test --list` existed. Yes documentation would satiate me. In the end it's just about being about to get the info you want easily. So long as that is possible, I'm all for the smartest solution from a software perspective.
