### ISSUE TITLE
Adaptive time stepping with embedded Runge-Kutta and/or CFL

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC#298]
Adaptive time stepping with embedded Runge-Kutta. RK23 most likely - computing RHSs for RK3 then using them to compute the update for RK2 and RK3 (2nd and 3rd order accurate versions of RK), then the difference between them is a measure of time step error. Involves a tuning parameter that has to be added to the inputs.

**Comment by sbryngelson** [comment]
@anandrdbz I think you had something like this? or maybe @lee-hyeoksu? or @wilfonba? I cannot remember. This would be separate from the sub-grid bubble case and just for general simulations.

**Comment by lee-hyeoksu** [comment]
@sbryngelson I implemented adaptive time stepping in `s_compute_bubble_source`. It would be possible to implement the adaptive time stepping for general simulations in a similar way. But before working on it, I would like to understand the needs of adaptive time stepping.

In sub-grid bubble simulation, especially where the convective time scale is much larger than the bubble response time scale, the adaptive time stepping is needed to run simulation efficiently. In this case, we can set the default `dt` that corresponds to `CFL = 0.7` or something, no matter how small `dt` the sub-grid bubble requires.

Other than sub-grid bubble simulation, what kinds of simulation do you expect to get benefits from adaptive time stepping?

**Comment by lee-hyeoksu** [comment]
@sbryngelson I got it. Thanks for explanation. If no one has done it so far, I would do it.

**Comment by sbryngelson** [comment]
That would be great!
