### ISSUE TITLE
More documentation for Windows machines

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC#308]
More build, test, and visualization documentation for Windows machines / WSL. Especially because these users tend to be less *nix-savvy.

**Comment by henryleberre** [comment]
I am not sure if anyone uses Windows natively after I added support for it, but I do realize now that my PR #307 does not provide a way to run MFC interactively on Windows. It should be trivial to add support for it, however.

**Comment by sbryngelson** [comment]
I guess what I really mean is a WSL+MFC guide. maybe there's nothing more to do, but I've watched people try to install MFC who aren't familiar with WSL and more handholding is needed. But definitely don't need to support "native Windows".

**Comment by sbryngelson** [comment]
@ChrisZYJ what did we decide here? I'm open to multiple options. If we decide that we "don't work" with Windows without WSL then we should probably add that to the documentation. If we can work with "regular" Windows then we can add that.

**Comment by sbryngelson** [comment]
@ChrisZYJ, never mind, I forgot you fixed this with PR #533 (w/ @henryleberre). Thanks guys. Closing.

**Comment by ChrisZYJ** [comment]
Yes I added more detailed documentations for WSL too!

**Comment by sbryngelson** [comment]
@ChrisZYJ i appreciate it!
