### ISSUE TITLE
CI runs twice for PR pushes

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC#312]
When committing to a PR the CI runs twice, once for [push] action and once for [pull_request]. This is for _all_ commits to that PR. This doesn't seem right, but I _think_ it has a clean solution. It might already be in @henryleberre's upcoming PR.

**Comment by henryleberre** [comment]
@sbryngelson I think this issue is specific to PRs made from branches of this repository. I think that only keeping `on: [push, workflow_dispatch]` is all we need but I haven't checked.

**Comment by sbryngelson** [comment]
@henryleberre ah - you're correct. Ok, this can just be closed.
