### ISSUE TITLE
Sanity check on Device <--> Host memory transfers on GPU simulations

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC#329]
A recent profile of @anshgupta1234's branch revealed several memory transfers between host and device within a time step. They are short in the grand scheme of things because the case is small, but I could imagine this being problematic otherwise. I am posting some nsight sys screenshots here that should be investigated. Some of them appear to be moving data but are not associated with Ansh's IBM implementation (seemingly).

![Screenshot 2024-02-05 at 10 38 58](https://github.com/MFlowCode/MFC/assets/39740593/b06bf9ce-5666-4bf5-83d3-2ae07de4ee2d)
![Screenshot 2024-02-05 at 10 39 39](https://github.com/MFlowCode/MFC/assets/39740593/88ef66d8-73b2-4d63-b3c7-1d52d4b0b77a)
![Screenshot 2024-02-05 at 10 41 08](https://github.com/MFlowCode/MFC/assets/39740593/70d7209b-a59d-4feb-894c-32654e75331e)
![Screenshot 2024-02-05 at 10 43 47](https://github.com/MFlowCode/MFC/assets/39740593/2a69917f-4fb0-49ed-8ac5-fe3397252eb5)

**Comment by anshgupta1234** [comment]
@sbryngelson it was without the  `!$acc parallel loop`

**Comment by sbryngelson** [comment]
Can you add the acc loop back in, run it with 1M grid cells in 2D for 10 time steps, then send me the nsys profile again? @anshgupta1234

**Comment by sbryngelson** [comment]
Closing this, the compute sections look fine in the new profile. Any stray uploads are just local variables, they only appear important because the IBM update takes so little time but in practice they do not matter.
