### ISSUE TITLE
Documentation formatting bugs

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC#34]
<img width="828" alt="Screenshot 2022-11-01 at 16 51 10" src="https://user-images.githubusercontent.com/39740593/199338614-53389731-658a-4333-b7e3-99f0925d2c4e.png">
<img width="690" alt="Screenshot 2022-11-01 at 16 51 19" src="https://user-images.githubusercontent.com/39740593/199338615-8f2876ea-b60c-4c48-8677-23aed7464079.png">
<img width="1053" alt="Screenshot 2022-11-01 at 16 52 01" src="https://user-images.githubusercontent.com/39740593/199338616-48860685-8ba4-4e81-a9da-e3ef351e17ef.png">

Attached are three places where the documentation formatting seems to have gone awry.

**Comment by henryleberre** [comment]
I was able to fix all of these issues except for the last one. It renders correctly if you view the file on GitHub but - for some reason - MathJax stops working when it encounters `\dot`. This is supposed to be supported, however.

**Comment by sbryngelson** [comment]
what about \cody or similar
