### ISSUE TITLE
[bug] Rebuilding HDF5 

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC#352]
We appear to (fully) rebuild HDF5 with every instantiation of `./mfc.sh run [...] -t post_process` (at least on GPU). It takes non-negligible time (at least a few minutes).

* Computer: Phoenix
* Mode: Interactive

**Comment by sbryngelson** [comment]
Update: This is still happening. @henryleberre, can you try it on your end and confirm there isn't a fix? I just re-confirmed that this still happens (rebuilds HDF5 and Silo every post-process run). I'm, of course, willing to tolerate this, but if there's a simple fix, we should leave this issue open.

**Comment by henryleberre** [comment]
@sbryngelson Not sure. Maybe #365 had something to do with this?

**Comment by sbryngelson** [comment]
Maybe. This problem is salient on slower machines or slow internet. At least this is what I found the other day testing on a MacOS VM.
