### ISSUE TITLE
More benchmarks and longer benchmarks

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC#363]
* More benchmarks are needed (3D cases that are homogeneous in 2 of the dimensions might be easiest to setup).
* Longer benchmarks are needed (more time steps, e.g.) for GPU cases, which run quickly and are thus vulnerable to small runtime differences. This can be passed into the `case.py` benchmark case via an argument that contains the device type, like `examples/weak_scaling`.

**Comment by wilfonba** [comment]
This is on my ToDo list.
