### ISSUE TITLE
Helper functions?

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC#45]
It seems like there are "helper functions" peppered around the codebase. These are doing things like computing finite difference coefficients, applying divergence theorems, etc. etc. 

Can we (1) make a list of these and then, after review, (2) move them all to a common "helper" module?

**Comment by sbryngelson** [comment]
Putting these in a markdown list here:

* Pre-process
    * m_global_parameters
        * s_comp_n_from_cons 
        * s_comp_n_from_prim
        * s_quad
        * s_simpson
    * m_initial_condition
        * s_convert_cylindrical_to_cartesian_coord
        * s_convert_cylindrical_to_spherical_coord
        * All the s_<patch type> functions could go in a m_patches module
    * m_start_up
        * All the patch-checking functions could go in a m_check_patches module

* Simulation
    * m_cbc
        * All the s_compute_<bc> functions could go in a m_compute_cbc module 
    * m_derived_variables
        * s_compute_finite_difference_coefficients 
    * m_global_parameters
        * s_comp_n_from_cons 
        * s_comp_n_from_prim 
        * s_quad
        * s_simpson
        * m_qbmm
        * f_quad
        * f_quad2D 
    * m_viscous
        * s_apply_scalar_divergence_theorem
        * s_compute_fd_gradient
* Post-process
    * m_derived_variables
        * s_compute_finite_difference_coefficients
    * m_global_parameters
        * s_comp_n_from_cons
        * s_comp_n_from_prim 
        * s_quad
        * s_simpson

**Comment by sbryngelson** [comment]
This is a great start. I think almost all of this is right. I would encourage someone to start a fork or branch focused on this. I suspect that moving around the stuff in `m_cbc` will be more cumbersome and should perhaps be left for the end.

**Comment by wilfonba** [comment]
@anshgupta1234 I've added you as a collaborator to my fork of MFC. I have a branch called refactoring for this

**Comment by sbryngelson** [comment]
@anandrdbz please leave comments here

**Comment by anshgupta1234** [comment]
> @anshgupta1234 I've added you as a collaborator to my fork of MFC. I have a branch called refactoring for this

Thank you! I'll work on it over winter break.

**Comment by wilfonba** [comment]
@sbryngelson this should be closed
