### ISSUE TITLE
Refactor for new variable conversion and modularize sound speed

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC#48]
From here: 
https://github.com/MFlowCode/MFC/issues/13#issuecomment-1340966703

We see that we compute the primitive variables "by hand" several times throughout the code.
This happens in `m_data_output` and some other places as well.
Now that @anshgupta1234 has made the routines nice and simple for this, we should call those instead. 

Also, the speed of sound `c` is computed by hand in several places, though this could be moved out to `common/`. `c` is also sometimes called things like `c_avg` or `c_L` or `c_R`.

**Comment by sbryngelson** [comment]
For example, see this 
https://github.com/MFlowCode/MFC/blob/83528f12647f283cf0475abf17b635d0d73538c7/src/simulation/m_data_output.f90#L1645-L2048

**Comment by sbryngelson** [comment]
and this
https://github.com/MFlowCode/MFC/blob/83528f12647f283cf0475abf17b635d0d73538c7/src/simulation/m_data_output.f90#L693-L756

**Comment by anshgupta1234** [comment]
Update: `s_compute_speed_of_sound` has now been implemented on `anshgupta1234/fix_48`. Now moving on to refactoring for new variable conversion

**Comment by anshgupta1234** [comment]
This should perhaps be closed now?

**Comment by sbryngelson** [comment]
closed with #86
