### ISSUE TITLE
Nsight Systems profiling NVTX blocks are broken

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC#501]
For NVIDIA GPU Nsight Systems profiling, the NVTX blocks were, at some point, broken. It is unclear why, though it seems like it should be easy to track down. An example is in the image below for a 3D case.

Broken (current):
![Screenshot 2024-07-03 at 14 27 18](https://github.com/MFlowCode/MFC/assets/39740593/1660684a-99de-4415-9208-c59878b38c86)

Working (old):
<img width="2015" alt="Screenshot 2023-05-05 at 09 57 57" src="https://github.com/MFlowCode/MFC/assets/39740593/98d4b7ed-fee2-42f1-8ba1-fb6cdb950a51">

**Comment by AiredaleDev** [comment]
Out of curiosity, do you know when you most recently creating a working profile? I figured the fastest way I could address this is to determine which commit broke profiling.

**Comment by sbryngelson** [comment]
I am not sure. I suspect it was either the PR that introduced AMD GPU support (I think @anandrdbz as primary author but it has like 20 contributors), or @wilfonba's PR that abstracted out all RHS functionality to different subroutines. I'm not sure which (or it could be something else).
