### ISSUE TITLE
Silo files wrong in buffer regions for immersed boundaries.

### ISSUE THREAD

**Issue by wilfonba** [MFlowCode/MFC#513]
All interior points of immersed boundaries should be set to a constant value to make them clearer in visualizations. This is no longer the case, as shown in the attached photo.
![bug](https://github.com/MFlowCode/MFC/assets/48168887/df9c365c-260a-499e-8c89-5c863c147bac)

While technically a bug, #496 makes this feature nearly irrelevant, so I'm not sure what direction this should go.

**Comment by sbryngelson** [comment]
I would merge a PR for this so long as it doesn't make the code more complex.

**Comment by wilfonba** [comment]
I mostly meant if it even makes sense to fix, or if this feature could just be removed given the addition of IB markers in the silo files.

**Comment by sbryngelson** [comment]
It doesn't make much difference to me.

**Comment by wilfonba** [comment]
I'll just fix it then. I can't imagine it would add many lines

**Comment by sbryngelson** [comment]
Or do the reverse and remove the code forcing the flow in the IBM to be stationary... though fixing this seems easier. But being consistent seems to make most sense.

**Comment by wilfonba** [comment]
This was an artifact of a Paraview filter

**Comment by sbryngelson** [comment]
reopening because this appears real (it's also seen in visit).

**Comment by sbryngelson** [comment]
@Sam-Briney @wilfonba did we decide what to do with this? @Sam-Briney do you plan on fixing it, or leaving it alone?

**Comment by Sam-Briney** [comment]
@sbryngelson I had not planned on making this a high priority since it is possible to overlay the IB markers

**Comment by sbryngelson** [comment]
Works for me. Closing.
