### ISSUE TITLE
Linear theory comparison broken still

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC#575]
https://mflowcode.github.io/documentation/md_examples.html

Linear theory comparison image still broken after #573

**Comment by wilfonba** [comment]
It works on my machine with Google Chrome. I'm not sure what's going wrong.
![image](https://github.com/user-attachments/assets/824457e3-1643-4177-974b-0edbc03d750e)

**Comment by sbryngelson** [comment]
Nevermind, mine was loading from my old cache.
