### ISSUE TITLE
MFC gets @henryleberre's pyrometheus

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC#628]
```console
mfc: (venv) (Re)Installing mfc.sh's Python dependencies (via Pip).
Collecting pyrometheus@ git+https://github.com/henryleberre/pyrometheus.git@multi-lang-part-2 (from -r /Users/spencer/Downloads/MFC/toolchain/requirements.txt (line 28))
  Cloning https://github.com/henryleberre/pyrometheus.git (to revision multi-lang-part-2)
```

Can Esteban grant us access to the host repo, and we can just work off of that? Of course, we may need to submit a PR of some sort first.

**Comment by henryleberre** [comment]
@sbryngelson I actually do have a PR open for it: pyrometheus/pyrometheus#84. I need to remove the last commit therefrom and fix it in MFC (it's just a symbol that's defined in pyro and also in MFC). That commit just made it `private`. I'll get around it by including everything in MFC from pyro except that one symbol.

**Comment by sbryngelson** [comment]
Aside from fixing it on your (our) end, just bug Esteban to help get this merged. I expect this will not be a Silo-like situation 😉

**Comment by henryleberre** [comment]
I already did! Removing that commit right now, however, will cause current builds to fail.

**Comment by sbryngelson** [comment]
Current MFC builds or Pyro "builds"? I assume the former. What would require non-breaking builds? Sorry, I haven't followed that Pyro PR or, embarrassingly, the triaging of the CheMFC roll-in to MFC. Do you see an easy way to set it up so it builds now, without rolling in all of your current CheMFC head? 

That said, if we are prepared to pull in "all" of CheMFC "soon" then this issue is moot and can be closed.
