### ISSUE TITLE
Beginner's doubts.

### ISSUE THREAD

**Issue by VaLiuqqq** [MFlowCode/MFC#649]
Hello,

I am a beginner in MFC. I find MFC to be very different from other open source programs.

Other open source programs need to write their own programming syntax and program files (for example, through loops or judgment statements to get what they need), and need users to conceive their own programming logic (calling various functions in the program to complete their requirements).

But MFC gets the final result by editing the input file (case.py). I would like to know if I want to make changes to MFC, can I only change the corresponding source file in .src? If I want to output some statement that says the result I have to change the fortran file in src? (Can't customize the output?)

Finally, as a beginner of MFC, after I understand the user documentation, are there any other suggestions you can give me to further understand and use MFC?

Best wishes!

**Comment by sbryngelson** [comment]
If you want to change what the code does, you change the source files in `src/`, if you want to change the specific problem it is solving, you change `case.py`. Thanks for your interest in MFC!

**Comment by VaLiuqqq** [comment]
Okay, thanks!
I'll come back and ask for your advice when I have problems in learning MFC.~
