### ISSUE TITLE
about the realisation of viscous and surface tension models

### ISSUE THREAD

**Issue by VaLiuqqq** [MFlowCode/MFC#652]
hello，

I have two questions:

The first question: I found that MFC has models and applications for viscosity and surface tension in Cartesian coordinate system by reading Meng's paper. However, I didn't find a logical in the MFC input file on whether to call these two models or not. 
In the MFC user documentation I found "When these parameters are undefined, fluids are treated as inviscid. Details of the implementation of viscosity in MFC can be found in Coralic (2015)". With this statement, may I ask if the viscosity and surface tension models can be used automatically in a 2D_shockdroplet just by giving the values of the three parameters Re(1), Re(1) and sigma in the fluid material?
Or is it by calling the above two models by the three parameters mu_l0, ss, and pv that I found in Ensemble-Averaged Bubble Model?(I think it should not be this one)

The second question: building on the first question, i.e. the ability to use viscous and surface tension models in a Cartesian coordinate system. I know that the above two models in MFC are only used in Cartesian coordinate system and cannot be used in column coordinates. So in 3D_shockdroplet, if I choose Cartesian coordinate system instead of column coordinate system, is it possible to use viscous and surface tension model for simulation?

Can you give me the answer to these two questions? @sbryngelson 

Best wishes!

**Comment by VaLiuqqq** [comment]
Can anyone answer my two questions above?

hello, @sbryngelson 
Did you see my question and answer them?

**Comment by sbryngelson** [comment]
You can use the examples for how to use surface tension and viscosity. Thanks!
