### ISSUE TITLE
About the use of viscous effects re(1), re(2) and surface tension sigma?

### ISSUE THREAD

**Issue by VaLiuqqq** [MFlowCode/MFC#676]
hello，

As we can see from the fluid material's in the documentation, _Re(1)_ and _Re(2)_ can only be used with model_eqns = 2, and _sigma_ can only be used with model_eqns = 3. The other parameters _cv_, _qv_ and _qvp_ of model_eqns = 3 are thermodynamic related parameters and have nothing to do with viscous effects. 
The result is that the effects of shear viscosity _Re(1)_ and volume viscosity _Re(2)_ cannot be taken into account in the case of surface tension _sigma_. 
I saw in 3D_recovering_sphere that Re(1) was dropped in the comment # when _sigma_ was used again. I don't know what it means to imply us. 

And is there a way to account for the effects of viscous effects in the context of surface tension sigma?

Best wishes!

![image](https://github.com/user-attachments/assets/adfdfe65-bb81-40e0-b37b-9f9e35897803)
![image](https://github.com/user-attachments/assets/75782527-cf0a-4814-a617-439adf3023b6)

**Comment by sbryngelson** [comment]
Viscosity and the 6-equation model should be compatible. 

Otherwise, I'm not sure what your question is, and this certainly isn't a GitHub issue. You can raise a question on Slack.

**Comment by VaLiuqqq** [comment]
ok，Since I see documentation that viscosity can only be used with model_eqns=2, I have this question because I see in the program that both viscosity and surface tension can be used.

If I have a question, how do I ask it in Slack? I don't use Slack and can only find a place to communicate on Github.  😔╮(╯▽╰)╭

**Comment by VaLiuqqq** [comment]
hello, @sbryngelson 

I have already download the Slack？So how do I join MFC channel to discuss some questions？
Are you going to invite me or should I apply？

**Comment by wilfonba** [comment]
@VaLiuqqq I don't have the invite link for Slack and can't find it right now. As of now, surface tension is only supported with the 6-equation model. Extending it to work with the 5-eqn model is trivial, but I decided not to do so when implementing it based on the discussion in Schmidmayer et al. 2017 (https://www.sciencedirect.com/science/article/pii/S0021999117300116). Making it work with the 5-eqn model only requires adding the flux for the color function to the 5-eqn HLLC Riemann solver. I have been running 6-eqn simulation with viscosity and surface tension for a while now, indicating the documentation is outdated. The case should run with viscosity, surface tension, and the 6-equation model just fine
