### ISSUE TITLE
Add `viscous` flag instead of `any(Re_size > 0)`

### ISSUE THREAD

**Issue by henryleberre** [MFlowCode/MFC#677]
Per this request https://github.com/MFlowCode/MFC/pull/653#discussion_r1828101258:
> yes please create a GH issue for someone to add this :D

Replace uses of `if (any(Re_size > 0))` with `if (viscous)` (create a new flag for it).

```console
MFC:[chemfc-up] $ grep 'Re_size > 0' -R src/ | wc -l
      82
```

**Comment by sbryngelson** [comment]
Similar to this issue for surface tension: https://github.com/MFlowCode/MFC/issues/668
