### ISSUE TITLE
Test the 2Dshock-droplet with "sigma"

### ISSUE THREAD

**Issue by VaLiuqqq** [MFlowCode/MFC#720]
When I tested 2Dshock-droplet with "sigma", the number of cfl was more than 1.Then I changed the code to adaptive dt.
But when I changed to adaptive dt, the delta t is too small.Why does this problem arise? How do I deal with this problem?

![image](https://github.com/user-attachments/assets/9849fe50-fa4c-49f2-a7c1-a39158be9f5d)

![image](https://github.com/user-attachments/assets/a9f08c61-6bea-450c-81c2-d6032abde24d)

**Comment by sbryngelson** [comment]
Closed in lieu of the discussion topic.
