### ISSUE TITLE
`post_process` tests

### ISSUE THREAD

**Issue by henryleberre** [MFlowCode/MFC#76]
_Duplicate_ of https://github.com/MFlowCode/MFC-develop/issues/116 as discussed in #74.

**Comment by sbryngelson** [comment]
adding @anshgupta1234 to assignees. 
I think we want to stage the tests here:

1. "Dumb test": with `parallel_IO = 'T'` we want to be sure the parallel files are actually created and that they do not create `NaN`s or an out-of-bounds number. You can do the latter via a call to `h5dump` on the files.
2. "Smarter test": Do a `silodiff` on golden silo files and compare them to the created ones. 

1 is easier and we should do this first, then perhaps add 2 later.

**Comment by sbryngelson** [comment]
Closed with #107
