### ISSUE TITLE
Instability in Hypoelastic Simulations

### ISSUE THREAD

**Issue by ChrisZYJ** [MFlowCode/MFC#771]
### Description

Commit 10b2209 (#727) introduces instability in some hypoelastic simulations compared to previous commit 108805c7.

### Test Case

- Simulation: Simple acoustic wave propagation with sound waves from left focused at a centered stone

- Case file: [case_hypo.txt](https://github.com/user-attachments/files/18234216/case_hypo.txt)

#### Step 300 of the simulation (with commit 10b2209):
![image](https://github.com/user-attachments/assets/b92ce729-a164-476b-8a27-6dba6590a901)

#### Comparison with the previous commit 108805c7 (top:108805c7 ; bottom:10b2209):
https://github.com/user-attachments/assets/3b05a2a1-08b2-4e0c-ac97-44c6df4f97ae

### Environment & Configuration
- Ubuntu 22.04.4 LTS
- GNU 11.4.0
- Using CPU with both debug enabled and disabled

**Comment by sbryngelson** [comment]
Unsure on this, perhaps @mrodrig6 can comment or @mcarcana

**Comment by mrodrig6** [comment]
@ChrisZYJ Are you running this on two ranks? It might be worth running this on one rank. 

If it is ran on 1 rank, we will need to investigate which terms in the hypoelastic formulation are breaking the symmetry.

**Comment by ChrisZYJ** [comment]
@mrodrig6 Thanks for getting back to me! The same instability occurs with 1 rank or more ranks.

I'm creating a new PR to revert the changes to just the hypoelasticity module for now, if that's okay. It should not affect your PR in progress.
