### ISSUE TITLE
Document undocumented patches

### ISSUE THREAD

**Issue by henryleberre** [MFlowCode/MFC#88]
Currently, patch types 14 to 19 are undocumented and they perhaps should be.

While on the topic, wouldn't it be clearer if each patch type had its own derived type within `patch_icpp(i)`? For example, an STL patch (#83) could be defined as:
```
patch_icpp(2)%geometry:      20,
patch_icpp(2)%stl%filepath:  'path/to/stl/file`,
patch_icpp(2)%stl%scale(2):  1.0,
patch_icpp(2)%stl%offset(3): 0.25,
```

This, in a sense, self-documents what properties each patch type can have. Every attribute that is common to all patches would be in the base `patch_icpp(i)%` scope.

**Comment by sbryngelson** [comment]
> Currently, patch types 14 to 19 are undocumented and they perhaps should be.

Agreed 

> While on the topic, wouldn't it be clearer if each patch type had its own derived type within `patch_icpp(i)`? For example, an STL patch (https://github.com/MFlowCode/MFC/issues/83) could be defined as

This seems to make sense. I'm glad to look at a PR on the issue (can start with MicroFC if that's easier). Want to make sure we don't end up with too many nested inheritances if possible (will just make things more complicated). 

However, I do agree that right now the use of the variables associated with each `patch_icpp` type is hard to pin down if you haven't used it before.
