### ISSUE TITLE
CMake Requirements

### ISSUE THREAD

**Issue by js-spratt** [MFlowCode/MFC#92]
Current version of MFC appears to require CMake v3.20 or newer, and thus no longer compiles on Expanse (which has CMake 3.18 only).

Either the build system should be modified to allow older versions of CMake, or an appropriate check should be run to check for a recent enough CMake version when compiling (and re-download CMake if the installed version if too old).

**Comment by henryleberre** [comment]
Thank you @js-spratt for letting me know. I added this system a few months ago so I just needed to bump the CMake versions to reflect what is currently required.
