### ISSUE TITLE
Some outdated documentation

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC#94]
1. [Running](https://github.com/MFlowCode/MFC/blob/master/docs/documentation/running.md) (bottom) has outdated syntax (I believe). 
2. Please add how-to-profile information to the documentation, including information about how to use `nsight sys` and `ncu`. Reminder that for `ncu` one requires `--cache-control none, --clock-control none` for multi-rank jobs.

**Comment by sbryngelson** [comment]
Not sure of status of this. Please have a look @anshgupta1234

**Comment by anshgupta1234** [comment]
@sbryngelson 1. isn't an issue I believe, but there is no documentation for 2. 

I personally am inexperienced with `nsight sys` and `ncu`, but I can learn and then add it to the documentation if you'd like :)

**Comment by sbryngelson** [comment]
I recommend learning to use them on MFC.

**Comment by anshgupta1234** [comment]
I believe this is closed.
