### ISSUE TITLE
The input keywords for QBMM are missing in the documentation

### ISSUE THREAD

**Issue by wilfonba** [MFlowCode/MFC#97]
There is no mention in the documentation of the following input keywords:

    - qbmm
    - dist_type
    - poly_sigma
    - R0_type
    - sigR
    - sigV
    - rhoRV

**Comment by sbryngelson** [comment]
Assigning to @anandrdbz since he will know what these are.

**Comment by anandrdbz** [comment]
Added in the latest PR
